### ISSUE TITLE
Console Showing Warning and Error Massage

### ISSUE THREAD

**Issue by MarcoSuteja** [MiroslavShard/chemistry-ar#2]
I try to use XR and improving this project and console showing this error massage and warning, mostly like "No active UnityEngine.XR.ARSubsystem is available", Please anybody help.

![image](https://github.com/MiroslavShard/chemistry-ar/assets/90343618/068c6255-93a6-4b98-b180-d57bc0a6a245)
![image](https://github.com/MiroslavShard/chemistry-ar/assets/90343618/f690d3dc-3c7b-43c4-b83d-270bfd2ff171)

>

**Comment by MiroslavShard** [comment]
Hi @MarcoSuteja! As I see, there are no errors in the screenshots you attached. The warning **_No active UnityEngine.XR.ARSubsystems.XRSessionSubsystem is available_** means that Unity Editor does not support AR. Try building and running this project on your Android or iOS device and check if this error is present.

You can also check the XR Simulation if you want to test it in the Unity Editor: https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.0/manual/xr-simulation/simulation.html

Let me know if the issue is resolved, or provide additional information so I can look into it further. Thanks!
